### ISSUE TITLE
More clarification please.

### ISSUE THREAD

**Issue by ctf0** [Chumper/Zipper#28]
there are a couple of methods i just don't get , basicly when to use any of the below
```
addString($filename, $content)
close()
home()
zip($fileName) // does exactly the same as make ,so is it for ?
```
also i cant quite understand the main example ,do they all related to each other or each suppose to do something on its own ,am asking because they are using the same object so some lines doesn't make any sense.

**Comment by Chumper** [comment]
i  merged a PR that added documentation, do you still need a hint somewhere?

**Comment by ctf0** [comment]
yeap ,i still don't get exactly what they are for.

**Comment by Chumper** [comment]
`addString()` will add a file inside the zip which path and name you specify with the first parameter, the second parameter will be the content of the file.

`close()` will close the archive and will write all changes to the disk, if you created a zip folder you can now pass it to the user as download.

`home()` will reset the internal folder pointer to /
That means you can normally do something like this
```php
->folder('test')->addString('testFile.txt','myContent')
->home()
->addString('homeFile','myContent')
```
Which will create a file `testFile` inside the folder `test` and which will create `homeFile` at the root of the zip.

`zip()` does the same as `make()` but `make()` is supposed to guess the repository implementation.
Since we do just have a zip implementation it is not very useful, but later with phar or gz you could do `make('archive.gz')` and the implementation will guess the right repository.

**Comment by ctf0** [comment]
okey thanx ,now i have a couple more >>
how to remove a folder from a zip ?
how to append to a file with `addString()` ? ,currently it wipe the file and add only the new content

**Comment by Chumper** [comment]
Both are currently not directly supported.
Atm you can only remove files or a list of files, you can not pass a path there. That would be something we could add to edit existing zips.

The seconds one does also not work because we dont have an `append` method.
We could add that too, but a solution for your problem would be to store the content in a variable and write it at the end into the zip file

**Comment by ctf0** [comment]
okey ,thanx for ur help :).
